export const FETCH_AGGREGATIONS_REQUEST = 'FETCH_AGGREGATIONS_REQUEST';
export const FETCH_AGGREGATIONS_SUCCESS = 'FETCH_AGGREGATIONS_SUCCESS';
export const FETCH_AGGREGATIONS_FAILURE = 'FETCH_AGGREGATIONS_FAILURE';
