export const FETCH_ALARMS_REQUEST = 'FETCH_ALARMS_REQUEST';
export const FETCH_ALARMS_SUCCESS = 'FETCH_ALARMS_SUCCESS';
export const FETCH_ALARMS_FAILURE = 'FETCH_ALARMS_FAILURE';

export const FETCH_ALARM_REQUEST = 'FETCH_ALARM_REQUEST';
export const FETCH_ALARM_SUCCESS = 'FETCH_ALARM_SUCCESS';
export const FETCH_ALARM_FAILURE = 'FETCH_ALARM_FAILURE';

export const FETCH_ALARM_CONFIG_REQUEST = 'FETCH_ALARM_CONFIG_REQUEST';
export const FETCH_ALARM_CONFIG_SUCCESS = 'FETCH_ALARM_CONFIG_SUCCESS';
export const FETCH_ALARM_CONFIG_FAILURE = 'FETCH_ALARM_CONFIG_FAILURE';

export const FILTER_ALARMS = 'FILTER_ALARMS';

export const SELECT_ALARM_RESOURCE_TYPE = 'SELECT_ALARM_RESOURCE_TYPE';

export const CREATE_ALARM_REQUEST = 'CREATE_ALARM_REQUEST';
export const CREATE_ALARM_SUCCESS = 'CREATE_ALARM_SUCCESS';
export const CREATE_ALARM_FAILURE = 'CREATE_ALARM_FAILURE';

export const DELETE_ALARM_REQUEST = 'DELETE_ALARM_REQUEST';
export const DELETE_ALARM_SUCCESS = 'DELETE_ALARM_SUCCESS';
export const DELETE_ALARM_FAILURE = 'DELETE_ALARM_FAILURE';

export const UPDATE_ALARM_REQUEST = 'UPDATE_ALARM_REQUEST';
export const UPDATE_ALARM_SUCCESS = 'UPDATE_ALARM_SUCCESS';
export const UPDATE_ALARM_FAILURE = 'UPDATE_ALARM_FAILURE';

export const ADD_ALARM_RULE_REQUEST = 'ADD_ALARM_RULE_REQUEST';
export const ADD_ALARM_RULE_SUCCESS = 'ADD_ALARM_RULE_SUCCESS';
export const ADD_ALARM_RULE_FAILURE = 'ADD_ALARM_RULE_FAILURE';

export const ADD_ALARM_RESOURCE_REQUEST = 'ADD_ALARM_RESOURCE_REQUEST';
export const ADD_ALARM_RESOURCE_SUCCESS = 'ADD_ALARM_RESOURCE_SUCCESS';
export const ADD_ALARM_RESOURCE_FAILURE = 'ADD_ALARM_RESOURCE_FAILURE';

export const ADD_ALARM_NOTIFICATION_REQUEST = 'ADD_ALARM_NOTIFICATION_REQUEST';
export const ADD_ALARM_NOTIFICATION_SUCCESS = 'ADD_ALARM_NOTIFICATION_SUCCESS';
export const ADD_ALARM_NOTIFICATION_FAILURE = 'ADD_ALARM_NOTIFICATION_FAILURE';

export const DELETE_ALARM_RULE_REQUEST = 'DELETE_ALARM_RULE_REQUEST';
export const DELETE_ALARM_RULE_SUCCESS = 'DELETE_ALARM_RULE_SUCCESS';
export const DELETE_ALARM_RULE_FAILURE = 'DELETE_ALARM_RULE_FAILURE';

export const DELETE_ALARM_RESOURCE_REQUEST = 'DELETE_ALARM_RESOURCE_REQUEST';
export const DELETE_ALARM_RESOURCE_SUCCESS = 'DELETE_ALARM_RESOURCE_SUCCESS';
export const DELETE_ALARM_RESOURCE_FAILURE = 'DELETE_ALARM_RESOURCE_FAILURE';

export const DELETE_ALARM_NOTIFICATION_REQUEST = 'DELETE_ALARM_NOTIFICATION_REQUEST';
export const DELETE_ALARM_NOTIFICATION_SUCCESS = 'DELETE_ALARM_NOTIFICATION_SUCCESS';
export const DELETE_ALARM_NOTIFICATION_FAILURE = 'DELETE_ALARM_NOTIFICATION_FAILURE';
