export const FETCH_ALARMS_REQUEST = 'FETCH_ALARMS_REQUEST';
export const FETCH_ALARMS_SUCCESS = 'FETCH_ALARMS_SUCCESS';
export const FETCH_ALARMS_FAILURE = 'FETCH_ALARMS_FAILURE';
export const FILTER_ALARMS = 'FILTER_ALARMS';
