export const FETCH_BACKUPS_REQUEST = 'FETCH_BACKUPS_REQUEST';
export const FETCH_BACKUPS_SUCCESS = 'FETCH_BACKUPS_SUCCESS';
export const FETCH_BACKUPS_FAILURE = 'FETCH_BACKUPS_FAILURE';
export const FILTER_BACKUPS = 'FILTER_BACKUPS';
