export const FETCH_BARE_METALS_REQUEST = 'FETCH_BARE_METALS_REQUEST';
export const FETCH_BARE_METALS_SUCCESS = 'FETCH_BARE_METALS_SUCCESS';
export const FETCH_BARE_METALS_FAILURE = 'FETCH_BARE_METALS_FAILURE';
export const FILTER_BARE_METALS = 'FILTER_BARE_METALS';
