export const FETCH_BARE_METALS_REQUEST = 'FETCH_BARE_METALS_REQUEST';
export const FETCH_BARE_METALS_SUCCESS = 'FETCH_BARE_METALS_SUCCESS';
export const FETCH_BARE_METALS_FAILURE = 'FETCH_BARE_METALS_FAILURE';
export const FILTER_BARE_METALS = 'FILTER_BARE_METALS';
export const DELETE_BARE_METAL_REQUEST = 'DELETE_BARE_METAL_REQUEST';
export const DELETE_BARE_METAL_SUCCESS = 'DELETE_BARE_METAL_SUCCESS';
export const DELETE_BARE_METAL_FAILURE = 'DELETE_BARE_METAL_FAILURE';
