export const FETCH_DISKS_REQUEST = 'FETCH_DISKS_REQUEST';
export const FETCH_DISKS_SUCCESS = 'FETCH_DISKS_SUCCESS';
export const FETCH_DISKS_FAILURE = 'FETCH_DISKS_FAILURE';
export const FILTER_DISKS = 'FILTER_DISKS';
