export const FETCH_FIREWALLS_REQUEST = 'FETCH_FIREWALLS_REQUEST';
export const FETCH_FIREWALLS_SUCCESS = 'FETCH_FIREWALLS_SUCCESS';
export const FETCH_FIREWALLS_FAILURE = 'FETCH_FIREWALLS_FAILURE';
export const FILTER_FIREWALLS = 'FILTER_FIREWALLS';
