export const FETCH_FIREWALLS_REQUEST = 'FETCH_FIREWALLS_REQUEST';
export const FETCH_FIREWALLS_SUCCESS = 'FETCH_FIREWALLS_SUCCESS';
export const FETCH_FIREWALLS_FAILURE = 'FETCH_FIREWALLS_FAILURE';
export const FILTER_FIREWALLS = 'FILTER_FIREWALLS';
export const DELETE_FIREWALL_REQUEST = 'DELETE_FIREWALL_REQUEST';
export const DELETE_FIREWALL_SUCCESS = 'DELETE_FIREWALL_SUCCESS';
export const DELETE_FIREWALL_FAILURE = 'DELETE_FIREWALL_FAILURE';
