export const FETCH_FLOATING_IPS_REQUEST = 'FETCH_FLOATING_IPS_REQUEST';
export const FETCH_FLOATING_IPS_SUCCESS = 'FETCH_FLOATING_IPS_SUCCESS';
export const FETCH_FLOATING_IPS_FAILURE = 'FETCH_FLOATING_IPS_FAILURE';
export const FILTER_FLOATING_IPS = 'FILTER_FLOATING_IPS';
export const DELETE_FLOATING_IP_REQUEST = 'DELETE_FLOATING_IP_REQUEST';
export const DELETE_FLOATING_IP_SUCCESS = 'DELETE_FLOATING_IP_SUCCESS';
export const DELETE_FLOATING_IP_FAILURE = 'DELETE_FLOATING_IP_FAILURE';
