export const FETCH_FLOATING_IPS_REQUEST = 'FETCH_FLOATING_IPS_REQUEST';
export const FETCH_FLOATING_IPS_SUCCESS = 'FETCH_FLOATING_IPS_SUCCESS';
export const FETCH_FLOATING_IPS_FAILURE = 'FETCH_FLOATING_IPS_FAILURE';
export const FILTER_FLOATING_IPS = 'FILTER_FLOATING_IPS';
