export const FETCH_INSTANCES_REQUEST = 'FETCH_INSTANCES_REQUEST';
export const FETCH_INSTANCES_SUCCESS = 'FETCH_INSTANCES_SUCCESS';
export const FETCH_INSTANCES_FAILURE = 'FETCH_INSTANCES_FAILURE';
export const FILTER_INSTANCES = 'FILTER_INSTANCES';
export const FETCH_INSTANCE_REQUEST = 'FETCH_INSTANCE_REQUEST';
export const FETCH_INSTANCE_SUCCESS = 'FETCH_INSTANCE_SUCCESS';
export const FETCH_INSTANCE_FAILURE = 'FETCH_INSTANCE_FAILURE';
