export const FETCH_INSTANCES_REQUEST = 'FETCH_INSTANCES_REQUEST';
export const FETCH_INSTANCES_SUCCESS = 'FETCH_INSTANCES_SUCCESS';
export const FETCH_INSTANCES_FAILURE = 'FETCH_INSTANCES_FAILURE';

export const FETCH_INSTANCE_CONFIG_REQUEST = 'FETCH_INSTANCE_CONFIG_REQUEST';
export const FETCH_INSTANCE_CONFIG_SUCCESS = 'FETCH_INSTANCE_CONFIG_SUCCESS';
export const FETCH_INSTANCE_CONFIG_FAILURE = 'FETCH_INSTANCE_CONFIG_FAILURE';

export const FILTER_INSTANCES = 'FILTER_INSTANCES';

export const FETCH_INSTANCE_REQUEST = 'FETCH_INSTANCE_REQUEST';
export const FETCH_INSTANCE_SUCCESS = 'FETCH_INSTANCE_SUCCESS';
export const FETCH_INSTANCE_FAILURE = 'FETCH_INSTANCE_FAILURE';

export const CREATE_INSTANCE_REQUEST = 'CREATE_INSTANCE_REQUEST';
export const CREATE_INSTANCE_SUCCESS = 'CREATE_INSTANCE_SUCCESS';
export const CREATE_INSTANCE_FAILURE = 'CREATE_INSTANCE_FAILURE';

export const DELETE_INSTANCE_REQUEST = 'DELETE_INSTANCE_REQUEST';
export const DELETE_INSTANCE_SUCCESS = 'DELETE_INSTANCE_SUCCESS';
export const DELETE_INSTANCE_FAILURE = 'DELETE_INSTANCE_FAILURE';

export const UPDATE_INSTANCE_REQUEST = 'UPDATE_INSTANCE_REQUEST';
export const UPDATE_INSTANCE_SUCCESS = 'UPDATE_INSTANCE_SUCCESS';
export const UPDATE_INSTANCE_FAILURE = 'UPDATE_INSTANCE_FAILURE';

export const DELETE_KEYPAIR_REQUEST = 'DELETE_KEYPAIR_REQUEST';
export const DELETE_KEYPAIR_SUCCESS = 'DELETE_KEYPAIR_SUCCESS';
export const DELETE_KEYPAIR_FAILURE = 'DELETE_KEYPAIR_FAILURE';

export const DELETE_NETWORK_REQUEST = 'DELETE_NETWORK_REQUEST';
export const DELETE_NETWORK_SUCCESS = 'DELETE_NETWORK_SUCCESS';
export const DELETE_NETWORK_FAILURE = 'DELETE_NETWORK_FAILURE';

export const DELETE_VOLUME_REQUEST = 'DELETE_VOLUME_REQUEST';
export const DELETE_VOLUME_SUCCESS = 'DELETE_VOLUME_SUCCESS';
export const DELETE_VOLUME_FAILURE = 'DELETE_VOLUME_FAILURE';

export const DELETE_SNAPSHOT_REQUEST = 'DELETE_SNAPSHOT_REQUEST';
export const DELETE_SNAPSHOT_SUCCESS = 'DELETE_SNAPSHOT_SUCCESS';
export const DELETE_SNAPSHOT_FAILURE = 'DELETE_SNAPSHOT_FAILURE';

export const ADD_SNAPSHOT_REQUEST = 'ADD_SNAPSHOT_REQUEST';
export const ADD_SNAPSHOT_SUCCESS = 'ADD_SNAPSHOT_SUCCESS';
export const ADD_SNAPSHOT_FAILURE = 'ADD_SNAPSHOT_FAILURE';

export const ADD_KEYPAIR_REQUEST = 'ADD_KEYPAIR_REQUEST';
export const ADD_KEYPAIR_SUCCESS = 'ADD_KEYPAIR_SUCCESS';
export const ADD_KEYPAIR_FAILURE = 'ADD_KEYPAIR_FAILURE';

export const ADD_NETWORK_REQUEST = 'ADD_NETWORK_REQUEST';
export const ADD_NETWORK_SUCCESS = 'ADD_NETWORK_SUCCESS';
export const ADD_NETWORK_FAILURE = 'ADD_NETWORK_FAILURE';

export const ADD_VOLUME_REQUEST = 'ADD_VOLUME_REQUEST';
export const ADD_VOLUME_SUCCESS = 'ADD_VOLUME_SUCCESS';
export const ADD_VOLUME_FAILURE = 'ADD_VOLUME_FAILURE';
