export const FETCH_KEYPAIRS_REQUEST = 'FETCH_KEYPAIRS_REQUEST';
export const FETCH_KEYPAIRS_SUCCESS = 'FETCH_KEYPAIRS_SUCCESS';
export const FETCH_KEYPAIRS_FAILURE = 'FETCH_KEYPAIRS_FAILURE';

export const FILTER_KEYPAIRS = 'FILTER_KEYPAIRS';

export const CREATE_KEYPAIR_REQUEST = 'CREATE_KEYPAIR_REQUEST';
export const CREATE_KEYPAIR_SUCCESS = 'CREATE_KEYPAIR_SUCCESS';
export const CREATE_KEYPAIR_FAILURE = 'CREATE_KEYPAIR_FAILURE';

export const DELETE_KEYPAIR_REQUEST = 'DELETE_KEYPAIR_REQUEST';
export const DELETE_KEYPAIR_SUCCESS = 'DELETE_KEYPAIR_SUCCESS';
export const DELETE_KEYPAIR_FAILURE = 'DELETE_KEYPAIR_FAILURE';

