export const FETCH_KEYPAIRS_REQUEST = 'FETCH_KEYPAIRS_REQUEST';
export const FETCH_KEYPAIRS_SUCCESS = 'FETCH_KEYPAIRS_SUCCESS';
export const FETCH_KEYPAIRS_FAILURE = 'FETCH_KEYPAIRS_FAILURE';
export const FILTER_KEYPAIRS = 'FILTER_KEYPAIRS';
