export const FETCH_NETWORKS_REQUEST = 'FETCH_NETWORKS_REQUEST';
export const FETCH_NETWORKS_SUCCESS = 'FETCH_NETWORKS_SUCCESS';
export const FETCH_NETWORKS_FAILURE = 'FETCH_NETWORKS_FAILURE';

export const FILTER_NETWORKS = 'FILTER_NETWORKS';

export const FETCH_NETWORKS_COUNT_REQUEST = 'FETCH_NETWORKS_COUNT_REQUEST';
export const FETCH_NETWORKS_COUNT_SUCCESS = 'FETCH_NETWORKS_COUNT_SUCCESS';
export const FETCH_NETWORKS_COUNT_FAILURE = 'FETCH_NETWORKS_COUNT_FAILURE';

export const FETCH_NETWORK_REQUEST = 'FETCH_NETWORK_REQUEST';
export const FETCH_NETWORK_SUCCESS = 'FETCH_NETWORK_SUCCESS';
export const FETCH_NETWORK_FAILURE = 'FETCH_NETWORK_FAILURE';

export const DELETE_NETWORK_REQUEST = 'DELETE_NETWORK_REQUEST';
export const DELETE_NETWORK_SUCCESS = 'DELETE_NETWORK_SUCCESS';
export const DELETE_NETWORK_FAILURE = 'DELETE_NETWORK_FAILURE';

export const UPDATE_NETWORK_REQUEST = 'UPDATE_NETWORK_REQUEST';
export const UPDATE_NETWORK_SUCCESS = 'UPDATE_NETWORK_SUCCESS';
export const UPDATE_NETWORK_FAILURE = 'UPDATE_NETWORK_FAILURE';

export const CREATE_NETWORK_REQUEST = 'CREATE_NETWORK_REQUEST';
export const CREATE_NETWORK_SUCCESS = 'CREATE_NETWORK_SUCCESS';
export const CREATE_NETWORK_FAILURE = 'CREATE_NETWORK_FAILURE';
