export const FETCH_NETWORKS_REQUEST = 'FETCH_NETWORKS_REQUEST';
export const FETCH_NETWORKS_SUCCESS = 'FETCH_NETWORKS_SUCCESS';
export const FETCH_NETWORKS_FAILURE = 'FETCH_NETWORKS_FAILURE';
export const FILTER_NETWORKS = 'FILTER_NETWORKS';
export const FETCH_NETWORKS_COUNT_REQUEST = 'FETCH_NETWORKS_COUNT_REQUEST';
export const FETCH_NETWORKS_COUNT_SUCCESS = 'FETCH_NETWORKS_COUNT_SUCCESS';
export const FETCH_NETWORKS_COUNT_FAILURE = 'FETCH_NETWORKS_COUNT_FAILURE';
