export const FETCH_NOTIFICATION_LISTS_REQUEST = 'FETCH_NOTIFICATION_LISTS_REQUEST';
export const FETCH_NOTIFICATION_LISTS_SUCCESS = 'FETCH_NOTIFICATION_LISTS_SUCCESS';
export const FETCH_NOTIFICATION_LISTS_FAILURE = 'FETCH_NOTIFICATION_LISTS_FAILURE';
export const FILTER_NOTIFICATION_LISTS = 'FILTER_NOTIFICATION_LISTS';
