export const FETCH_NOTIFICATION_LISTS_REQUEST = 'FETCH_NOTIFICATION_LISTS_REQUEST';
export const FETCH_NOTIFICATION_LISTS_SUCCESS = 'FETCH_NOTIFICATION_LISTS_SUCCESS';
export const FETCH_NOTIFICATION_LISTS_FAILURE = 'FETCH_NOTIFICATION_LISTS_FAILURE';

export const FILTER_NOTIFICATION_LISTS = 'FILTER_NOTIFICATION_LISTS';

export const FETCH_NOTIFICATION_LIST_REQUEST = 'FETCH_NOTIFICATION_LIST_REQUEST';
export const FETCH_NOTIFICATION_LIST_SUCCESS = 'FETCH_NOTIFICATION_LIST_SUCCESS';
export const FETCH_NOTIFICATION_LIST_FAILURE = 'FETCH_NOTIFICATION_LIST_FAILURE';

export const UPDATE_NOTIFICATION_LIST_REQUEST = 'UPDATE_NOTIFICATION_LIST_REQUEST';
export const UPDATE_NOTIFICATION_LIST_SUCCESS = 'UPDATE_NOTIFICATION_LIST_SUCCESS';
export const UPDATE_NOTIFICATION_LIST_FAILURE = 'UPDATE_NOTIFICATION_LIST_FAILURE';

export const DELETE_NOTIFICATION_LIST_REQUEST = 'DELETE_NOTIFICATION_LIST_REQUEST';
export const DELETE_NOTIFICATION_LIST_SUCCESS = 'DELETE_NOTIFICATION_LIST_SUCCESS';
export const DELETE_NOTIFICATION_LIST_FAILURE = 'DELETE_NOTIFICATION_LIST_FAILURE';

export const CREATE_NOTIFICATION_LIST_REQUEST = 'CREATE_NOTIFICATION_LIST_REQUEST';
export const CREATE_NOTIFICATION_LIST_SUCCESS = 'CREATE_NOTIFICATION_LIST_SUCCESS';
export const CREATE_NOTIFICATION_LIST_FAILURE = 'CREATE_NOTIFICATION_LIST_FAILURE';

export const DELETE_NOTIFICATION_LIST_TERMINAL_REQUEST =
  'DELETE_NOTIFICATION_LIST_TERMINAL_REQUEST';
export const DELETE_NOTIFICATION_LIST_TERMINAL_SUCCESS =
  'DELETE_NOTIFICATION_LIST_TERMINAL_SUCCESS';
export const DELETE_NOTIFICATION_LIST_TERMINAL_FAILURE =
  'DELETE_NOTIFICATION_LIST_TERMINAL_FAILURE';

export const CREATE_NOTIFICATION_LIST_TERMINAL_REQUEST =
  'CREATE_NOTIFICATION_LIST_TERMINAL_REQUEST';
export const CREATE_NOTIFICATION_LIST_TERMINAL_SUCCESS =
  'CREATE_NOTIFICATION_LIST_TERMINAL_SUCCESS';
export const CREATE_NOTIFICATION_LIST_TERMINAL_FAILURE =
  'CREATE_NOTIFICATION_LIST_TERMINAL_FAILURE';
