export const FETCH_OPERATIONS_REQUEST = 'FETCH_OPERATIONS_REQUEST';
export const FETCH_OPERATIONS_SUCCESS = 'FETCH_OPERATIONS_SUCCESS';
export const FETCH_OPERATIONS_FAILURE = 'FETCH_OPERATIONS_FAILURE';
