export const FETCH_POOLS_REQUEST = 'FETCH_POOLS_REQUEST';
export const FETCH_POOLS_SUCCESS = 'FETCH_POOLS_SUCCESS';
export const FETCH_POOLS_FAILURE = 'FETCH_POOLS_FAILURE';

export const FETCH_POOL_CONFIG_REQUEST = 'FETCH_POOL_CONFIG_REQUEST';
export const FETCH_POOL_CONFIG_SUCCESS = 'FETCH_POOL_CONFIG_SUCCESS';
export const FETCH_POOL_CONFIG_FAILURE = 'FETCH_POOL_CONFIG_FAILURE';

export const CREATE_POOL_REQUEST = 'CREATE_POOL_REQUEST';
export const CREATE_POOL_SUCCESS = 'CREATE_POOL_SUCCESS';
export const CREATE_POOL_FAILURE = 'CREATE_POOL_FAILURE';

export const UPDATE_POOL_STACK_REQUEST = 'UPDATE_POOL_STACK_REQUEST';
export const UPDATE_POOL_STACK_SUCCESS = 'UPDATE_POOL_STACK_SUCCESS';
export const UPDATE_POOL_STACK_FAILURE = 'UPDATE_POOL_STACK_FAILURE';

export const CREATE_POOL_STACK_REQUEST = 'CREATE_POOL_STACK_REQUEST';
export const CREATE_POOL_STACK_SUCCESS = 'CREATE_POOL_STACK_SUCCESS';
export const CREATE_POOL_STACK_FAILURE = 'CREATE_POOL_STACK_FAILURE';
