export const FETCH_ROUTERS_REQUEST = 'FETCH_ROUTERS_REQUEST';
export const FETCH_ROUTERS_SUCCESS = 'FETCH_ROUTERS_SUCCESS';
export const FETCH_ROUTERS_FAILURE = 'FETCH_ROUTERS_FAILURE';
export const FILTER_ROUTERS = 'FILTER_ROUTERS';
