export const FETCH_SECURITY_GROUPS_REQUEST = 'FETCH_SECURITY_GROUPS_REQUEST';
export const FETCH_SECURITY_GROUPS_SUCCESS = 'FETCH_SECURITY_GROUPS_SUCCESS';
export const FETCH_SECURITY_GROUPS_FAILURE = 'FETCH_SECURITY_GROUPS_FAILURE';
export const FILTER_SECURITY_GROUPS = 'FILTER_SECURITY_GROUPS';
