export const FETCH_SECURITY_GROUPS_REQUEST = 'FETCH_SECURITY_GROUPS_REQUEST';
export const FETCH_SECURITY_GROUPS_SUCCESS = 'FETCH_SECURITY_GROUPS_SUCCESS';
export const FETCH_SECURITY_GROUPS_FAILURE = 'FETCH_SECURITY_GROUPS_FAILURE';
export const FILTER_SECURITY_GROUPS = 'FILTER_SECURITY_GROUPS';
export const DELETE_SECURITY_GROUP_REQUEST = 'DELETE_SECURITY_GROUP_REQUEST';
export const DELETE_SECURITY_GROUP_SUCCESS = 'DELETE_SECURITY_GROUP_SUCCESS';
export const DELETE_SECURITY_GROUP_FAILURE = 'DELETE_SECURITY_GROUP_FAILURE';
