export const FETCH_SNAPSHOTS_REQUEST = 'FETCH_SNAPSHOTS_REQUEST';
export const FETCH_SNAPSHOTS_SUCCESS = 'FETCH_SNAPSHOTS_SUCCESS';
export const FETCH_SNAPSHOTS_FAILURE = 'FETCH_SNAPSHOTS_FAILURE';
export const FILTER_SNAPSHOTS = 'FILTER_SNAPSHOTS';
