export const FETCH_STACKS_REQUEST = 'FETCH_STACKS_REQUEST';
export const FETCH_STACKS_SUCCESS = 'FETCH_STACKS_SUCCESS';
export const FETCH_STACKS_FAILURE = 'FETCH_STACKS_FAILURE';

export const FILTER_STACKS = 'FILTER_STACKS';

export const FETCH_STACK_REQUEST = 'FETCH_STACK_REQUEST';
export const FETCH_STACK_SUCCESS = 'FETCH_STACK_SUCCESS';
export const FETCH_STACK_FAILURE = 'FETCH_STACK_FAILURE';

export const DELETE_STACK_REQUEST = 'DELETE_STACK_REQUEST';
export const DELETE_STACK_SUCCESS = 'DELETE_STACK_SUCCESS';
export const DELETE_STACK_FAILURE = 'DELETE_STACK_FAILURE';

export const FETCH_STACK_CONFIG_REQUEST = 'FETCH_STACK_CONFIG_REQUEST';
export const FETCH_STACK_CONFIG_SUCCESS = 'FETCH_STACK_CONFIG_SUCCESS';
export const FETCH_STACK_CONFIG_FAILURE = 'FETCH_STACK_CONFIG_FAILURE';

export const UPDATE_STACK_REQUEST = 'UPDATE_STACK_REQUEST';
export const UPDATE_STACK_SUCCESS = 'UPDATE_STACK_SUCCESS';
export const UPDATE_STACK_FAILURE = 'UPDATE_STACK_FAILURE';

export const CREATE_STACK_REQUEST = 'CREATE_STACK_REQUEST';
export const CREATE_STACK_SUCCESS = 'CREATE_STACK_SUCCESS';
export const CREATE_STACK_FAILURE = 'CREATE_STACK_FAILURE';
