export const FETCH_SUBNETS_REQUEST = 'FETCH_SUBNETS_REQUEST';
export const FETCH_SUBNETS_SUCCESS = 'FETCH_SUBNETS_SUCCESS';
export const FETCH_SUBNETS_FAILURE = 'FETCH_SUBNETS_FAILURE';
export const FILTER_SUBNETS = 'FILTER_SUBNETS';
export const FETCH_SUBNETS_COUNT_REQUEST = 'FETCH_SUBNETS_COUNT_REQUEST';
export const FETCH_SUBNETS_COUNT_SUCCESS = 'FETCH_SUBNETS_COUNT_SUCCESS';
export const FETCH_SUBNETS_COUNT_FAILURE = 'FETCH_SUBNETS_COUNT_FAILURE';
