export const FETCH_VIRTUAL_NICS_REQUEST = 'FETCH_VIRTUAL_NICS_REQUEST';
export const FETCH_VIRTUAL_NICS_SUCCESS = 'FETCH_VIRTUAL_NICS_SUCCESS';
export const FETCH_VIRTUAL_NICS_FAILURE = 'FETCH_VIRTUAL_NICS_FAILURE';
export const FILTER_VIRTUAL_NICS = 'FILTER_VIRTUAL_NICS';
