export const FETCH_VOLUMES_REQUEST = 'FETCH_VOLUMES_REQUEST';
export const FETCH_VOLUMES_SUCCESS = 'FETCH_VOLUMES_SUCCESS';
export const FETCH_VOLUMES_FAILURE = 'FETCH_VOLUMES_FAILURE';

export const FILTER_VOLUMES = 'FILTER_VOLUMES';

export const FETCH_VOLUME_REQUEST = 'FETCH_VOLUME_REQUEST';
export const FETCH_VOLUME_SUCCESS = 'FETCH_VOLUME_SUCCESS';
export const FETCH_VOLUME_FAILURE = 'FETCH_VOLUME_FAILURE';

export const UPDATE_VOLUME_REQUEST = 'UPDATE_VOLUME_REQUEST';
export const UPDATE_VOLUME_SUCCESS = 'UPDATE_VOLUME_SUCCESS';
export const UPDATE_VOLUME_FAILURE = 'UPDATE_VOLUME_FAILURE';

export const DELETE_VOLUME_BACKUP_REQUEST = 'DELETE_VOLUME_BACKUP_REQUEST';
export const DELETE_VOLUME_BACKUP_SUCCESS = 'DELETE_VOLUME_BACKUP_SUCCESS';
export const DELETE_VOLUME_BACKUP_FAILURE = 'DELETE_VOLUME_BACKUP_FAILURE';

export const ADD_VOLUME_BACKUP_REQUEST = 'ADD_VOLUME_BACKUP_REQUEST';
export const ADD_VOLUME_BACKUP_SUCCESS = 'ADD_VOLUME_BACKUP_SUCCESS';
export const ADD_VOLUME_BACKUP_FAILURE = 'ADD_VOLUME_BACKUP_FAILURE';

export const FETCH_VOLUME_CONFIG_REQUEST = 'FETCH_VOLUME_CONFIG_REQUEST';
export const FETCH_VOLUME_CONFIG_SUCCESS = 'FETCH_VOLUME_CONFIG_SUCCESS';
export const FETCH_VOLUME_CONFIG_FAILURE = 'FETCH_VOLUME_CONFIG_FAILURE';

export const CREATE_VOLUME_REQUEST = 'CREATE_VOLUME_REQUEST';
export const CREATE_VOLUME_SUCCESS = 'CREATE_VOLUME_SUCCESS';
export const CREATE_VOLUME_FAILURE = 'CREATE_VOLUME_FAILURE';

export const DELETE_VOLUME_REQUEST = 'DELETE_VOLUME_REQUEST';
export const DELETE_VOLUME_SUCCESS = 'DELETE_VOLUME_SUCCESS';
export const DELETE_VOLUME_FAILURE = 'DELETE_VOLUME_FAILURE';
